import type { Word } from './types';

export const words: Word[] = [
  { category: 'animal', name: 'cat' },
  { category: 'animal', name: 'dog' },
  { category: 'animal', name: 'bird' },
  { category: 'fruit', name: 'apple' },
  { category: 'fruit', name: 'banana' },
  { category: 'fruit', name: 'orange' },
  { category: 'color', name: 'red' },
  { category: 'color', name: 'blue' },
  { category: 'color', name: 'green' },
];

export const alphabet = [
  'A',
  'B',
  'C',
  'D',
  'E',
  'F',
  'G',
  'H',
  'I',
  'J',
  'K',
  'L',
  'M',
  'N',
  'O',
  'P',
  'Q',
  'R',
  'S',
  'T',
  'U',
  'V',
  'W',
  'X',
  'Y',
  'Z',
];
